/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
/**
 *
 * @author barth
 */
public class GestionMultiEnsemble extends javax.swing.JFrame {
    MultiEnsembleTab e1;
    MultiEnsembleTab e2;
    
    /**
     * Creates new form GestionMultiEnsemble
     */
    public GestionMultiEnsemble() {
        initComponents();
        this.setTitle("Multi Ensemble");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        demandeElement1 = new javax.swing.JLabel();
        demandeElement2 = new javax.swing.JLabel();
        saisieElement1 = new javax.swing.JTextField();
        saisieElement2 = new javax.swing.JTextField();
        entrerElement1 = new javax.swing.JLabel();
        entrerElement2 = new javax.swing.JLabel();
        validElement1 = new javax.swing.JButton();
        validElement2 = new javax.swing.JButton();
        ajout1 = new javax.swing.JTextField();
        ajout2 = new javax.swing.JTextField();
        Union = new javax.swing.JButton();
        Intersection = new javax.swing.JButton();
        demandeSupp1 = new javax.swing.JLabel();
        demandeSupp2 = new javax.swing.JLabel();
        elementSupp1 = new javax.swing.JTextField();
        elementSupp2 = new javax.swing.JTextField();
        validSupp1 = new javax.swing.JButton();
        validSupp2 = new javax.swing.JButton();
        saisieEntier1 = new javax.swing.JTextField();
        saisieEntier2 = new javax.swing.JTextField();
        validEntier1 = new javax.swing.JButton();
        validEntier2 = new javax.swing.JButton();
        retourMenu = new javax.swing.JButton();
        enumAleatoire1 = new javax.swing.JButton();
        enumerateur1 = new javax.swing.JButton();
        enumAleatoire2 = new javax.swing.JButton();
        enumerateur2 = new javax.swing.JButton();
        removeAll1 = new javax.swing.JButton();
        removeAll2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Affichage = new javax.swing.JTextArea();
        unionStatic = new javax.swing.JButton();
        iinterStatic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        demandeElement1.setText("Combien d'éléments voulez-vous ajouter au multi ensemble e2 ?");

        demandeElement2.setText("Combien d'éléments voulez-vous ajouter au multi ensemble e1 ?");

        saisieElement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisieElement1ActionPerformed(evt);
            }
        });

        entrerElement1.setText("Entrer les éléments que vous voulez ajouter à e1 :");

        entrerElement2.setText("Entrer les éléments que vous voulez ajouter à e2 :");

        validElement1.setText("ok");
        validElement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validElement1ActionPerformed(evt);
            }
        });

        validElement2.setText("ok");
        validElement2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validElement2ActionPerformed(evt);
            }
        });

        Union.setText("Union");
        Union.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnionActionPerformed(evt);
            }
        });

        Intersection.setText("Intersection");
        Intersection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntersectionActionPerformed(evt);
            }
        });

        demandeSupp1.setText("Entrez les éléments que vous voulez supprimer dans e1 :");

        demandeSupp2.setText("Entrez les éléments que vous voulez supprimer dans e2 :");

        validSupp1.setText("ok");
        validSupp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validSupp1ActionPerformed(evt);
            }
        });

        validSupp2.setText("ok");
        validSupp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validSupp2ActionPerformed(evt);
            }
        });

        validEntier1.setText("ok");
        validEntier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validEntier1MouseClicked(evt);
            }
        });
        validEntier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validEntier1ActionPerformed(evt);
            }
        });

        validEntier2.setText("ok");
        validEntier2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validEntier2MouseClicked(evt);
            }
        });
        validEntier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validEntier2ActionPerformed(evt);
            }
        });

        retourMenu.setText("retour au menu");
        retourMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourMenuActionPerformed(evt);
            }
        });

        enumAleatoire1.setText("EnumAlea e1");
        enumAleatoire1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enumAleatoire1ActionPerformed(evt);
            }
        });

        enumerateur1.setText(" Enumerateur e1");
        enumerateur1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enumerateur1MouseClicked(evt);
            }
        });

        enumAleatoire2.setText("EnumAlea e2");
        enumAleatoire2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enumAleatoire2MouseClicked(evt);
            }
        });

        enumerateur2.setText(" Enumerateur e2");
        enumerateur2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enumerateur2MouseClicked(evt);
            }
        });

        removeAll1.setText("Remove All");
        removeAll1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeAll1MouseClicked(evt);
            }
        });

        removeAll2.setText("Remove All");
        removeAll2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeAll2MouseClicked(evt);
            }
        });

        Affichage.setColumns(20);
        Affichage.setRows(5);
        jScrollPane1.setViewportView(Affichage);

        unionStatic.setText("Union Static");
        unionStatic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unionStaticMouseClicked(evt);
            }
        });

        iinterStatic.setText("Inter Static");
        iinterStatic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iinterStaticMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Intersection, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(Union, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unionStatic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(demandeSupp1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(demandeSupp2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(217, 217, 217))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(enumAleatoire2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enumAleatoire1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enumerateur1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enumerateur2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iinterStatic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(181, 181, 181)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(retourMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(396, 396, 396)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(elementSupp2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(validSupp2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(removeAll2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(elementSupp1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(validSupp1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(removeAll1)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(demandeElement1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(saisieElement1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(validElement1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(saisieElement2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(validElement2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ajout1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entrerElement1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saisieEntier1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(validEntier1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ajout2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(entrerElement2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saisieEntier2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(validEntier2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(demandeElement2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(473, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saisieElement1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validElement1))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entrerElement1)
                            .addComponent(saisieEntier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validEntier1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajout1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(demandeElement1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saisieElement2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validElement2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entrerElement2)
                            .addComponent(saisieEntier2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validEntier2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(demandeSupp1)
                            .addComponent(elementSupp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validSupp1)
                            .addComponent(removeAll1)))
                    .addComponent(Union))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Intersection)
                            .addComponent(demandeSupp2)
                            .addComponent(elementSupp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validSupp2)
                            .addComponent(removeAll2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enumAleatoire1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enumerateur1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enumAleatoire2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enumerateur2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unionStatic)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iinterStatic)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(retourMenu)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(demandeElement2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(512, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {saisieElement1, validElement1});

        retourMenu.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validElement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validElement1ActionPerformed
        // TODO add your handling code here:
        int taille = Integer.parseInt(saisieElement1.getText());
        e1 = new MultiEnsembleTab(taille); 
    }//GEN-LAST:event_validElement1ActionPerformed

    private void validElement2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validElement2ActionPerformed
        // TODO add your handling code here:int taille = Integer.parseInt(saisieElement1.getText());
        int taille = Integer.parseInt(saisieElement2.getText());
        e2 = new MultiEnsembleTab(taille); 
        
    }//GEN-LAST:event_validElement2ActionPerformed

    private void validEntier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validEntier1ActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_validEntier1ActionPerformed

    private void validEntier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validEntier2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_validEntier2ActionPerformed

    private void UnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnionActionPerformed
        // TODO add your handling code here:
        e1.union(e2);
        Affichage.append("Union entre e1 et e2 : ");
        Affichage.append(e1.toString()+"\n");
    }//GEN-LAST:event_UnionActionPerformed

    private void IntersectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntersectionActionPerformed
        // TODO add your handling code here:
        e1.inter(e2);
        Affichage.append("Intersection entre e1 et e2 : ");
        Affichage.append(e2.toString()+"\n");
    }//GEN-LAST:event_IntersectionActionPerformed

    private void validSupp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validSupp1ActionPerformed
        // TODO add your handling code here:
        int element = Integer.parseInt(elementSupp1.getText());
        e1.remove(element);
        Affichage.append("Vous avez supprimez "+element+"\n\n");
        Affichage.append(e1.toString()+"\n");
        elementSupp1.setText("");
    }//GEN-LAST:event_validSupp1ActionPerformed

    private void validSupp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validSupp2ActionPerformed
        // TODO add your handling code here:
        int element = Integer.parseInt(elementSupp2.getText());
        e2.remove(element);
        Affichage.setText("Vous avez supprimez "+element+"\n\n");
        Affichage.append(e2.toString()+"\n");
        elementSupp1.setText("");
    }//GEN-LAST:event_validSupp2ActionPerformed

    private void retourMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourMenuActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourMenuActionPerformed

    private void saisieElement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisieElement1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saisieElement1ActionPerformed

    private void validEntier1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validEntier1MouseClicked
        // TODO add your handling code here:
        int element = Integer.parseInt(saisieEntier1.getText());
            try{
                 e1.add(element);
               
                 ajout1.setText(e1.toString());
                 saisieEntier1.setText("");
                 ajout1.setEnabled(true);
                 ajout1.requestFocusInWindow();
     
            }catch(ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null, "Vous ne pouvez ajouter un autre entier vous dépassez la taille", "Avertissement",
   JOptionPane.INFORMATION_MESSAGE);
                saisieEntier1.setText("");
            }
    }//GEN-LAST:event_validEntier1MouseClicked

    private void validEntier2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validEntier2MouseClicked
        // TODO add your handling code here:
        int element = Integer.parseInt(saisieEntier2.getText());
            try{
                 e2.add(element);
               
                 ajout2.setText(e2.toString());
                 saisieEntier2.setText("");
                 ajout2.setEnabled(true);
                 ajout2.requestFocusInWindow();
     
            }catch(ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null, "Vous ne pouvez ajouter un autre entier vous dépassez la taille", "Avertissement",
   JOptionPane.INFORMATION_MESSAGE);
                saisieEntier2.setText("");
            }
    }//GEN-LAST:event_validEntier2MouseClicked

    private void enumAleatoire1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enumAleatoire1ActionPerformed
        // TODO add your handling code here:
        Affichage.setText("");
        Affichage.append(e1.enumerateurAleatoire());
        
        
    }//GEN-LAST:event_enumAleatoire1ActionPerformed

    private void enumerateur1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enumerateur1MouseClicked
        // TODO add your handling code here:
        Affichage.setText("");
        Affichage.append(e1.enumerateur());
    }//GEN-LAST:event_enumerateur1MouseClicked

    private void enumAleatoire2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enumAleatoire2MouseClicked
        // TODO add your handling code here:
        Affichage.setText("");
        Affichage.append(e2.enumerateurAleatoire());
    }//GEN-LAST:event_enumAleatoire2MouseClicked

    private void enumerateur2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enumerateur2MouseClicked
        // TODO add your handling code here:
        Affichage.setText("");
        Affichage.append(e2.enumerateur());
    }//GEN-LAST:event_enumerateur2MouseClicked

    private void removeAll1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeAll1MouseClicked
        // TODO add your handling code here:
        int element = Integer.parseInt(elementSupp1.getText());
        e1.removeAll(element);
        Affichage.append("Vous avez supprimez les "+element+"\n\n");
        Affichage.append(e1.toString()+"\n");
        elementSupp1.setText("");
        
    }//GEN-LAST:event_removeAll1MouseClicked

    private void removeAll2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeAll2MouseClicked
        // TODO add your handling code here:
        int element = Integer.parseInt(elementSupp2.getText());
        e2.removeAll(element);
        Affichage.append("Vous avez supprimez les "+element+"\n\n");
        Affichage.append(e2.toString()+"\n");
        elementSupp2.setText("");
    }//GEN-LAST:event_removeAll2MouseClicked

    private void unionStaticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unionStaticMouseClicked
        // TODO add your handling code here:
        MultiEnsembleTab e3 = new MultiEnsembleTab();
        e3 = MultiEnsembleTab.union(e1,e2);
        Affichage.append("Union static entre e1 et e2 : \n");
        Affichage.append(e3.toString()+"\n\n");
    }//GEN-LAST:event_unionStaticMouseClicked

    private void iinterStaticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iinterStaticMouseClicked
        // TODO add your handling code here:
        MultiEnsembleTab e3 = new MultiEnsembleTab();
        e3 = MultiEnsembleTab.inter(e1,e2);
        Affichage.append("Intersection static entre e1 et e2 : \n");
        Affichage.append(e3.toString()+"\n\n");
    }//GEN-LAST:event_iinterStaticMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMultiEnsemble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMultiEnsemble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMultiEnsemble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMultiEnsemble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GestionMultiEnsemble().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Affichage;
    private javax.swing.JButton Intersection;
    private javax.swing.JButton Union;
    private javax.swing.JTextField ajout1;
    private javax.swing.JTextField ajout2;
    private javax.swing.JLabel demandeElement1;
    private javax.swing.JLabel demandeElement2;
    private javax.swing.JLabel demandeSupp1;
    private javax.swing.JLabel demandeSupp2;
    private javax.swing.JTextField elementSupp1;
    private javax.swing.JTextField elementSupp2;
    private javax.swing.JLabel entrerElement1;
    private javax.swing.JLabel entrerElement2;
    private javax.swing.JButton enumAleatoire1;
    private javax.swing.JButton enumAleatoire2;
    private javax.swing.JButton enumerateur1;
    private javax.swing.JButton enumerateur2;
    private javax.swing.JButton iinterStatic;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeAll1;
    private javax.swing.JButton removeAll2;
    private javax.swing.JButton retourMenu;
    private javax.swing.JTextField saisieElement1;
    private javax.swing.JTextField saisieElement2;
    private javax.swing.JTextField saisieEntier1;
    private javax.swing.JTextField saisieEntier2;
    private javax.swing.JButton unionStatic;
    private javax.swing.JButton validElement1;
    private javax.swing.JButton validElement2;
    private javax.swing.JButton validEntier1;
    private javax.swing.JButton validEntier2;
    private javax.swing.JButton validSupp1;
    private javax.swing.JButton validSupp2;
    // End of variables declaration//GEN-END:variables
}
