
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author barth
 */
public class Gestion_ensembe extends javax.swing.JFrame {
    EnsembleTab e;      
      EnsembleTab e2;
    /**
     * Creates new form Gestion_ensembe
     */
    public Gestion_ensembe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nbr_éléments1 = new java.awt.Label();
        saisieElement1 = new java.awt.TextField();
        validElement1 = new java.awt.Button();
        entrerElement = new java.awt.Label();
        saisieEntier = new java.awt.TextField();
        validEntier = new java.awt.Button();
        Ajout = new java.awt.TextField();
        saisieElement2 = new java.awt.TextField();
        validElement2 = new java.awt.Button();
        saisieEntier1 = new java.awt.TextField();
        entrerElement1 = new java.awt.Label();
        validEntier1 = new java.awt.Button();
        Nbr_éléments2 = new java.awt.Label();
        Ajout2 = new java.awt.TextField();
        DemandeSupp = new javax.swing.JLabel();
        DemandeSupp1 = new javax.swing.JLabel();
        ElementSupp = new javax.swing.JTextField();
        ElementSupp1 = new javax.swing.JTextField();
        ValidSupp = new javax.swing.JButton();
        ValidSupp1 = new javax.swing.JButton();
        enumAleatoire1 = new javax.swing.JButton();
        enumerateur1 = new javax.swing.JButton();
        enumAleatoire2 = new javax.swing.JButton();
        enumerateur2 = new javax.swing.JButton();
        Union = new javax.swing.JButton();
        Intersection = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Zone_affichage = new javax.swing.JTextArea();
        retourMenu = new javax.swing.JButton();
        unionStatic = new javax.swing.JButton();
        iinterStatic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ensemble");
        setBackground(new java.awt.Color(1, 147, 176));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(82, 93, 255));

        Nbr_éléments1.setText("Combien d'éléments souhaitez vous ajouter dans l'ensemble e1 ?");

        saisieElement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisieElement1ActionPerformed(evt);
            }
        });

        validElement1.setActionCommand("OK");
        validElement1.setLabel("ok");
        validElement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validElement1ActionPerformed(evt);
            }
        });

        entrerElement.setText("Entrez les éléments dans e1  (attention a ne pas dépasser la taille) :");

        saisieEntier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisieEntierActionPerformed(evt);
            }
        });

        validEntier.setLabel("ok");
        validEntier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validEntierMouseClicked(evt);
            }
        });
        validEntier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validEntierActionPerformed(evt);
            }
        });

        Ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutActionPerformed(evt);
            }
        });

        saisieElement2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisieElement2ActionPerformed(evt);
            }
        });

        validElement2.setActionCommand("OK");
        validElement2.setLabel("ok");
        validElement2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validElement2ActionPerformed(evt);
            }
        });

        entrerElement1.setText("Entrez les éléments dans e1  (attention a ne pas dépasser la taille) :");

        validEntier1.setLabel("ok");
        validEntier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validEntier1MouseClicked(evt);
            }
        });
        validEntier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validEntier1ActionPerformed(evt);
            }
        });

        Nbr_éléments2.setText("Combien d'éléments souhaitez vous ajouter dans l'ensemble e2 ?");

        Ajout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajout2ActionPerformed(evt);
            }
        });

        DemandeSupp.setText("Entrez les éléments que vous voulez supprimer dans e1 :");

        DemandeSupp1.setText("Entrez les éléments que vous voulez supprimer dans e2 :");

        ElementSupp.setMaximumSize(new java.awt.Dimension(25, 25));
        ElementSupp.setMinimumSize(null);
        ElementSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementSuppActionPerformed(evt);
            }
        });

        ElementSupp1.setMaximumSize(new java.awt.Dimension(25, 25));
        ElementSupp1.setMinimumSize(null);

        ValidSupp.setText("ok");
        ValidSupp.setMaximumSize(new java.awt.Dimension(25, 25));
        ValidSupp.setMinimumSize(null);
        ValidSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidSuppActionPerformed(evt);
            }
        });

        ValidSupp1.setText("ok");
        ValidSupp1.setMaximumSize(new java.awt.Dimension(25, 25));
        ValidSupp1.setMinimumSize(null);
        ValidSupp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidSupp1ActionPerformed(evt);
            }
        });

        enumAleatoire1.setText("EnumAlea e1");
        enumAleatoire1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enumAleatoire1ActionPerformed(evt);
            }
        });

        enumerateur1.setText(" Enumerateur e1");

        enumAleatoire2.setText("EnumAlea e1");
        enumAleatoire2.setActionCommand("EnumAlea e2");

        enumerateur2.setText(" Enumerateur e2");

        Union.setText("Union");
        Union.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnionActionPerformed(evt);
            }
        });

        Intersection.setText("Intersection");
        Intersection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntersectionActionPerformed(evt);
            }
        });

        Zone_affichage.setColumns(20);
        Zone_affichage.setRows(5);
        jScrollPane1.setViewportView(Zone_affichage);

        retourMenu.setText("retour au menu");
        retourMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourMenuActionPerformed(evt);
            }
        });

        unionStatic.setText("Union Static");
        unionStatic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unionStaticMouseClicked(evt);
            }
        });

        iinterStatic.setText("Inter Static");
        iinterStatic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iinterStaticMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enumAleatoire1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ajout2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(entrerElement1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(saisieEntier1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validEntier1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nbr_éléments2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saisieElement2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validElement2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nbr_éléments1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saisieElement1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validElement1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(entrerElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saisieEntier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validEntier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(retourMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(enumerateur1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(unionStatic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enumerateur2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(iinterStatic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enumAleatoire2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Intersection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Union, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DemandeSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ElementSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ValidSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DemandeSupp1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ElementSupp1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ValidSupp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(360, 360, 360))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {saisieEntier, validElement1, validEntier});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {saisieElement1, saisieElement2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ElementSupp, ElementSupp1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(validElement1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saisieElement1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Nbr_éléments1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saisieEntier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrerElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validEntier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(Ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nbr_éléments2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saisieElement2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validElement2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validEntier1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrerElement1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saisieEntier1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ajout2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Union)
                    .addComponent(DemandeSupp)
                    .addComponent(ElementSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValidSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Intersection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enumAleatoire1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enumerateur1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enumAleatoire2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enumerateur2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unionStatic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iinterStatic))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DemandeSupp1)
                            .addComponent(ElementSupp1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValidSupp1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1)))
                .addGap(62, 62, 62)
                .addComponent(retourMenu)
                .addGap(26, 26, 26))
        );

        validElement1.getAccessibleContext().setAccessibleName("OK");
        entrerElement1.getAccessibleContext().setAccessibleName("Entrez les éléments dans e2  (attention a ne pas dépasser la taille) :");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saisieElement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisieElement1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saisieElement1ActionPerformed

    private void validElement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validElement1ActionPerformed
        // TODO add your handling code here:
       /* if ((Integer.parseInt(saisieElement1.getText())) == 0 ){
            JOptionPane.showMessageDialog(null, " blah blah", "Text",
   JOptionPane.INFORMATION_MESSAGE);
        }*/
        int taille = Integer.parseInt(saisieElement1.getText());
       
        e = new EnsembleTab(taille); 
        
          
    }//GEN-LAST:event_validElement1ActionPerformed

    private void validEntierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validEntierActionPerformed
            
               
    }//GEN-LAST:event_validEntierActionPerformed

    private void validElement2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validElement2ActionPerformed
        // TODO add your handling code here:
        int taille = Integer.parseInt(saisieElement2.getText());
       
        e2 = new EnsembleTab(taille); 
    }//GEN-LAST:event_validElement2ActionPerformed

    private void validEntier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validEntier1ActionPerformed
        // TODO add your handling code here:
         
           // TODO add your handling code here:*
            
    }//GEN-LAST:event_validEntier1ActionPerformed

    private void saisieEntierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisieEntierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saisieEntierActionPerformed

    private void saisieElement2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisieElement2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saisieElement2ActionPerformed

    private void AjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjoutActionPerformed

    private void ValidSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidSuppActionPerformed
        // TODO add your handling code here:
        String newLine = System.getProperty("line.separator");
        int element = Integer.parseInt(ElementSupp.getText());
        e.remove(element);
        Zone_affichage.append("Vous avez supprimez "+element+"\n\n");
        Zone_affichage.append(e.toString()+"\n");
        ElementSupp.setText("");
    }//GEN-LAST:event_ValidSuppActionPerformed

    private void ElementSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementSuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElementSuppActionPerformed

    private void Ajout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajout2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ajout2ActionPerformed

    private void ValidSupp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidSupp1ActionPerformed
        // TODO add your handling code here:
            String newLine = System.getProperty("line.separator");
        int element = Integer.parseInt(ElementSupp1.getText());
        e2.remove(element);
       Zone_affichage.append("Vous avez supprimez "+element+"\n\n");
        Zone_affichage.append(e2.toString()+"\n");
        ElementSupp1.setText("");
        
    }//GEN-LAST:event_ValidSupp1ActionPerformed

    private void validEntierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validEntierMouseClicked
        // TODO add your handling code here:
            int element = Integer.parseInt(saisieEntier.getText());
            try{
                 e.add(element);
               
                 Ajout.setText(e.toString());
                 saisieEntier.setText("");
                 Ajout.setEnabled(true);
                 Ajout.requestFocusInWindow();
     
            }catch(ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null, "Vous ne pouvez ajouter un autre entier vous dépassez la taille", "Avertissement",
   JOptionPane.INFORMATION_MESSAGE);
                saisieEntier.setText("");
            }
           // TODO add your handling code here:*
            
    }//GEN-LAST:event_validEntierMouseClicked

    private void validEntier1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validEntier1MouseClicked
        // TODO add your handling code he
        int element = Integer.parseInt(saisieEntier1.getText());
        try{        
            e2.add(element);
            Ajout2.setText(e2.toString());
            saisieEntier1.setText("");
            Ajout2.setEnabled(true);
            Ajout2.requestFocusInWindow();
        }catch(ArrayIndexOutOfBoundsException e){
             JOptionPane.showMessageDialog(null, "Vous ne pouvez ajouter un autre entier vous dépassez la taille", "Avertissement",
   JOptionPane.INFORMATION_MESSAGE);
                saisieEntier1.setText("");
        }
         
    }//GEN-LAST:event_validEntier1MouseClicked

    private void enumAleatoire1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enumAleatoire1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_enumAleatoire1ActionPerformed

    private void UnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnionActionPerformed
        // TODO add your handling code here:
        e.union(e2);
        Zone_affichage.append("Union entre e1 et e2 : \n");
        Zone_affichage.append(e.toString()+"\n\n");
    }//GEN-LAST:event_UnionActionPerformed

    private void IntersectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntersectionActionPerformed
        // TODO add your handling code here:
        e.inter(e2);
        Zone_affichage.append("Intersection entre e1 et e2 : \n");
        Zone_affichage.append(e.toString()+"\n\n");
    }//GEN-LAST:event_IntersectionActionPerformed

    private void retourMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourMenuActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourMenuActionPerformed

    private void unionStaticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unionStaticMouseClicked
        // TODO add your handling code here:
        MultiEnsembleTab e3 = new MultiEnsembleTab();
        e3 = MultiEnsembleTab.union(e,e2);
        Zone_affichage.append("Union static entre e1 et e2 : \n");
        Zone_affichage.append(e3.toString()+"\n\n");
    }//GEN-LAST:event_unionStaticMouseClicked

    private void iinterStaticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iinterStaticMouseClicked
        // TODO add your handling code here:
        MultiEnsembleTab e3 = new MultiEnsembleTab();
        e3 = MultiEnsembleTab.inter(e,e2);
        Zone_affichage.append("Intersection static entre e1 et e2 : \n");
        Zone_affichage.append(e3.toString()+"\n\n");
    }//GEN-LAST:event_iinterStaticMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_ensembe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_ensembe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_ensembe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_ensembe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Gestion_ensembe b =new Gestion_ensembe();
                b.setLocationRelativeTo(null);   
                b.setVisible(true);
                    
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Ajout;
    private java.awt.TextField Ajout2;
    private javax.swing.JLabel DemandeSupp;
    private javax.swing.JLabel DemandeSupp1;
    private javax.swing.JTextField ElementSupp;
    private javax.swing.JTextField ElementSupp1;
    private javax.swing.JButton Intersection;
    private java.awt.Label Nbr_éléments1;
    private java.awt.Label Nbr_éléments2;
    private javax.swing.JButton Union;
    private javax.swing.JButton ValidSupp;
    private javax.swing.JButton ValidSupp1;
    private javax.swing.JTextArea Zone_affichage;
    private java.awt.Label entrerElement;
    private java.awt.Label entrerElement1;
    private javax.swing.JButton enumAleatoire1;
    private javax.swing.JButton enumAleatoire2;
    private javax.swing.JButton enumerateur1;
    private javax.swing.JButton enumerateur2;
    private javax.swing.JButton iinterStatic;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton retourMenu;
    private java.awt.TextField saisieElement1;
    private java.awt.TextField saisieElement2;
    private java.awt.TextField saisieEntier;
    private java.awt.TextField saisieEntier1;
    private javax.swing.JButton unionStatic;
    private java.awt.Button validElement1;
    private java.awt.Button validElement2;
    private java.awt.Button validEntier;
    private java.awt.Button validEntier1;
    // End of variables declaration//GEN-END:variables
}
